plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: 
description: This is my Jekyll website that is running Simple.css
lang: en
locale: en_GB
url: "https://sorenpeter.github.io/jekyll-simple-css/"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
