plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: YOUR NAME
description: This is my Jekyll website that is running Simple.css
lang: en
locale: en_GB

# To lean about url and baseurl see: https://mademistakes.com/mastering-jekyll/site-url-baseurl/
url: https://sorenpeter.github.io
baseurl: /jekyll-simple-css     


# RSS feeds
feed:
  posts_limit: 20
